channels:
- conda-forge
dependencies:
- python=3.8.12
- pip<=24.0
- pip:
  - mlflow==2.12.2
  - cloudpickle==3.0.0
  - numpy==1.24.3
  - packaging==24.0
  - pandas==2.0.3
  - protobuf==4.25.3
  - psutil==5.9.8
  - pyyaml==6.0.1
  - requests==2.31.0
  - scikeras==0.12.0
  - scikit-learn==1.3.2
  - scipy==1.10.1
  - tensorflow==2.13.1
name: mlflow-env
